# Generated by Django 5.1.15 on 2026-09-16 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(default='Hematology', max_length=100)),
                ('sample_type', models.CharField(default='Whole Blood (EDTA)', max_length=100)),
                ('container_type', models.CharField(default='Lavender Top Tube', max_length=100)),
                ('turnaround_hours', models.IntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lab_tests',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('priority', models.CharField(default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('PROCESSING', 'Processing'), ('RESULT_ENTERED', 'Result Entered'), ('VALIDATED', 'Validated'), ('REPORT_GENERATED', 'Report Generated')], default='COLLECTED', max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('is_flagged_abnormal', models.BooleanField(default=False)),
                ('technician_note', models.TextField(blank=True, null=True)),
                ('pathologist_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='lab.labtest')),
            ],
            options={
                'db_table': 'lab_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=100)),
                ('observed_value', models.CharField(max_length=50)),
                ('reference_range', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.laborder')),
            ],
            options={
                'db_table': 'lab_results',
            },
        ),
    ]
