# Generated by Django 5.1.15 on 2026-09-30 08:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(default='Hematology', max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('READY', 'Ready')], default='RUNNING', max_length=30)),
                ('last_pm_date', models.DateField(blank=True, null=True)),
                ('next_pm_date', models.DateField(blank=True, null=True)),
                ('service_contract', models.CharField(blank=True, max_length=200, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='laborder',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='critical_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='critical_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_critical_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='encounter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='is_flagged_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='is_retest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='laborder',
            name='retest_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='retest_routing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='sample_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_lab_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='labresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresult',
            name='flag',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High'), ('CRITICAL_LOW', 'Critical Low'), ('CRITICAL_HIGH', 'Critical High')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_delta_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='measured_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='previous_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='previous_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='technician_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.CharField(default='Hematology', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='container_color',
            field=models.CharField(default='Lavender', max_length=50),
        ),
        migrations.AddField(
            model_name='labtest',
            name='normal_ranges',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='labtest',
            name='parameters_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labtest',
            name='specimen_type',
            field=models.CharField(default='Whole Blood', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='stat_surcharge',
            field=models.CharField(default='Not offered', max_length=50),
        ),
        migrations.AddField(
            model_name='labtest',
            name='tat_minutes',
            field=models.IntegerField(default=240),
        ),
        migrations.AddField(
            model_name='labtest',
            name='tpa_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='priority',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('IN_ANALYSIS', 'In Analysis'), ('RESULTS_ENTERED', 'Results Entered'), ('REPORT_APPROVED', 'Report Approved'), ('CANCELLED', 'Cancelled'), ('COLLECTED', 'Collected'), ('PROCESSING', 'Processing'), ('RESULT_ENTERED', 'Result Entered'), ('VALIDATED', 'Validated'), ('REPORT_GENERATED', 'Report Generated')], default='ORDERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='reference_range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='unit',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='department',
            field=models.CharField(default='Diagnostic Lab', max_length=100),
        ),
        migrations.CreateModel(
            name='EquipmentMaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(default='PREVENTIVE', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='lab.equipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_equipment_maintenance_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.laborder')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='lab.labtest')),
            ],
            options={
                'db_table': 'lab_order_items',
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='lab.laborderitem'),
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('pathologist_remarks', models.TextField(blank=True, null=True)),
                ('report_pdf', models.TextField(blank=True, null=True)),
                ('digital_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('is_amended', models.BooleanField(default=False)),
                ('amendment_reason', models.TextField(blank=True, null=True)),
                ('amended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_lab_reports', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lab_reports', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='lab.laborder')),
            ],
            options={
                'db_table': 'lab_reports',
            },
        ),
    ]
