# Generated by Django 5.1.15 on 2026-10-08 13:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_bankstatement_banktransaction_budget_collectioncase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFinancialReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_key', models.CharField(max_length=50, unique=True)),
                ('period_range', models.CharField(max_length=100)),
                ('collections_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payments_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('receivables_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('payables_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('department_spending', models.JSONField(default=list)),
                ('summary_lines', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('shared_with_controller', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_weekly_reviews',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='committed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='budget',
            name='explanation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='head_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='budget',
            name='overrun_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='trail',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gstbatch',
            name='reviewed_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gstbatch',
            name='turnaround_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='receivable',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivable',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receivable',
            name='promise_missed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivable',
            name='promised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivable',
            name='recovery_priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='accounting.costcenter'),
        ),
        migrations.CreateModel(
            name='FinancialException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('reference_no', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('department_id', models.CharField(default='finance', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('investigating', 'Investigating'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='new', max_length=30)),
                ('source', models.CharField(default='system', max_length=150)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_financial_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_financial_exceptions',
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_fi_status_219d93_idx'), models.Index(fields=['type'], name='accounts_fi_type_e006ba_idx')],
            },
        ),
    ]
