# Generated by Django 5.1.15 on 2026-10-09 05:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_weeklyfinancialreview_budget_committed_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obs_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=150)),
                ('status', models.CharField(default='Open', max_length=30)),
                ('kind', models.CharField(default='obs', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_audit_observations',
            },
        ),
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=150)),
                ('due_date', models.CharField(max_length=50)),
                ('status', models.CharField(default='In Progress', max_length=30)),
                ('evidence_files', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_audit_requests',
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recon_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_no_masked', models.CharField(max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(default='2026-09', max_length=20)),
                ('book_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('statement_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(default='Unreconciled', max_length=50)),
                ('prepared_by_name', models.CharField(blank=True, max_length=150)),
                ('last_reconciled_label', models.CharField(blank=True, max_length=50)),
                ('exception_ref', models.CharField(blank=True, max_length=50)),
                ('ack_text', models.TextField(blank=True)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_bank_reconciliations',
            },
        ),
        migrations.CreateModel(
            name='ControlViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('control_name', models.CharField(max_length=150)),
                ('severity', models.CharField(default='High', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('who', models.CharField(blank=True, max_length=150)),
                ('refs', models.CharField(blank=True, max_length=255)),
                ('exposure_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('detected_date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Open', max_length=30)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_control_violations',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_type', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(default='2026-09', max_length=20)),
                ('status', models.CharField(default='Under Review', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('tie_outs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_financial_statements',
            },
        ),
        migrations.CreateModel(
            name='HighRiskItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ref', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('risk', models.CharField(default='High', max_length=20)),
                ('why', models.TextField(blank=True)),
                ('recv_date', models.CharField(blank=True, max_length=50)),
                ('key_values', models.JSONField(default=list)),
                ('documents', models.JSONField(default=list)),
                ('ack_text', models.TextField(blank=True)),
                ('status', models.CharField(default='Awaiting Controller', max_length=50)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_high_risk_items',
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('batch_type', models.CharField(default='Vendor', max_length=50)),
                ('source_bank_code', models.CharField(default='B2', max_length=50)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_date_label', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('item_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Awaiting Release', max_length=50)),
                ('prepared_by_name', models.CharField(blank=True, max_length=150)),
                ('approved_by_name', models.CharField(blank=True, max_length=150)),
                ('checks', models.JSONField(default=list)),
                ('ack_text', models.TextField(blank=True)),
                ('items_summary', models.JSONField(default=list)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_payment_batches',
            },
        ),
        migrations.CreateModel(
            name='PeriodReopenRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by_name', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('decision_comment', models.TextField(blank=True)),
                ('relocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_period_reopen_requests',
            },
        ),
        migrations.CreateModel(
            name='PolicyMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('owner_name', models.CharField(max_length=150)),
                ('next_review', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('change_data', models.JSONField(blank=True, null=True)),
                ('key_values', models.JSONField(default=list)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_policies',
            },
        ),
        migrations.CreateModel(
            name='QuarterCloseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=150)),
                ('status', models.CharField(default='For Review', max_length=30)),
                ('need_ref', models.CharField(blank=True, max_length=50)),
                ('need_statement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_quarter_close_items',
            },
        ),
        migrations.CreateModel(
            name='StatementFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_type', models.CharField(max_length=20)),
                ('line_key', models.CharField(max_length=50)),
                ('exception_no', models.CharField(max_length=50)),
                ('query_text', models.TextField()),
                ('raised_by_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_statement_flags',
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_key', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('line_type', models.CharField(default='l', max_length=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('comparison_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('variance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts_statement_lines',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('form', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('due_date', models.CharField(max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(default='Ready', max_length=50)),
                ('exceptions', models.JSONField(default=list)),
                ('link_exception', models.CharField(blank=True, max_length=50)),
                ('prepared_by_name', models.CharField(blank=True, max_length=150)),
                ('invoice_count', models.IntegerField(default=0)),
                ('ack_text', models.TextField(blank=True)),
                ('trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_tax_returns',
            },
        ),
        migrations.AddField(
            model_name='financialexception',
            name='linked_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='financialexception',
            name='severity',
            field=models.CharField(default='High', max_length=20),
        ),
        migrations.AddIndex(
            model_name='financialexception',
            index=models.Index(fields=['severity'], name='accounts_fi_severit_9ef9c3_idx'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='accounting.bankaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='financialstatement',
            unique_together={('statement_type', 'period')},
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payment_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='source_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_batches', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='periodreopenrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_period_reopens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodreopenrequest',
            name='period_lock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_requests', to='accounting.periodlock'),
        ),
        migrations.AddField(
            model_name='periodreopenrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_period_reopens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statementline',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.financialstatement'),
        ),
    ]
