# Generated by Django 5.1.15 on 2026-10-09 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_boardreport_budgetstrategyproposal_capexrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('patient_uhid', models.CharField(blank=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=150)),
                ('source_bill_no', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('refund_mode', models.CharField(default='cash', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid / Executed')], default='pending', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='accounting.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accounts_refunds', to=settings.AUTH_USER_MODEL)),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='accounting.financialevent')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='accounting.journal')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_accounts_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_refunds',
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_re_status_e40378_idx'), models.Index(fields=['source_bill_no'], name='accounts_re_source__ecbdc3_idx'), models.Index(fields=['patient_uhid'], name='accounts_re_patient_f5d74a_idx')],
            },
        ),
    ]
