# Generated by Django 5.1.15 on 2026-10-09 08:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantShareBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('department_id', models.CharField(default='OPD', max_length=50)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('doctor_count', models.IntegerField(default=0)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_tds_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.approvalrequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_consultant_batches', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journal')),
            ],
            options={
                'db_table': 'accounts_consultant_share_batches',
            },
        ),
        migrations.CreateModel(
            name='ConsultantShareItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('pan_aadhaar_linked', models.BooleanField(default=True)),
                ('case_count', models.IntegerField(default=1)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=18)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.consultantsharebatch')),
            ],
            options={
                'db_table': 'accounts_consultant_share_items',
            },
        ),
        migrations.CreateModel(
            name='IPDUnbilledTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('admission_number', models.CharField(blank=True, max_length=50)),
                ('patient_uhid', models.CharField(db_index=True, max_length=50)),
                ('patient_name', models.CharField(max_length=150)),
                ('ward_name', models.CharField(blank=True, max_length=100)),
                ('bed_number', models.CharField(blank=True, max_length=50)),
                ('payer_type', models.CharField(default='cash', max_length=50)),
                ('package_id', models.CharField(blank=True, max_length=50)),
                ('total_running_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('unbilled_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_deposits_held', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_charge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('final_invoice_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_ipd_unbilled_trackers',
                'indexes': [models.Index(fields=['status', 'patient_uhid'], name='accounts_ip_status_f6597a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTImplantConsignmentMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_no', models.CharField(blank=True, max_length=50)),
                ('implant_name', models.CharField(max_length=255)),
                ('invoiced_quantity', models.IntegerField()),
                ('usage_count', models.IntegerField()),
                ('variance_count', models.IntegerField(default=0)),
                ('match_status', models.CharField(default='matched', max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implant_consignment_match', to='accounting.vendorbill')),
            ],
            options={
                'db_table': 'accounts_ot_consignment_matches',
            },
        ),
        migrations.CreateModel(
            name='OTImplantUsageRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('patient_uhid', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=150)),
                ('admission_number', models.CharField(blank=True, max_length=50)),
                ('procedure_name', models.CharField(max_length=255)),
                ('theater_type', models.CharField(default='cath_lab', max_length=50)),
                ('implant_name', models.CharField(max_length=255)),
                ('implant_serial_no', models.CharField(blank=True, max_length=100)),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('vendor_name', models.CharField(default='Medline Surgicals Pvt Ltd', max_length=150)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.IntegerField(default=1)),
                ('used_at', models.DateTimeField()),
                ('surgeon_name', models.CharField(blank=True, max_length=150)),
                ('is_matched_to_invoice', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implant_usages', to='accounting.vendorbill')),
            ],
            options={
                'db_table': 'accounts_ot_implant_usages',
            },
        ),
    ]
