# Generated by Django 5.1.15 on 2026-10-09 09:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_consultantsharebatch_consultantshareitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPartnerInvoiceMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_lab', models.CharField(max_length=150)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('invoiced_count', models.IntegerField()),
                ('invoiced_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accrued_count', models.IntegerField()),
                ('accrued_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('count_variance', models.IntegerField(default=0)),
                ('amount_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('match_status', models.CharField(max_length=30)),
                ('exception_no', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('matched_at', models.DateTimeField(auto_now=True)),
                ('vendor_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_invoice_match', to='accounting.vendorbill')),
            ],
            options={
                'db_table': 'accounts_lab_partner_invoice_matches',
            },
        ),
        migrations.CreateModel(
            name='ServiceLineVolume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField(db_index=True)),
                ('department_id', models.CharField(max_length=50)),
                ('service_line', models.CharField(max_length=150)),
                ('unit', models.CharField(default='tests', max_length=50)),
                ('volume', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('outsourced_volume', models.IntegerField(default=0)),
                ('outsourced_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_service_line_volumes',
                'unique_together': {('business_date', 'department_id', 'service_line')},
            },
        ),
        migrations.CreateModel(
            name='OutsourcedTestAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('partner_lab', models.CharField(db_index=True, max_length=150)),
                ('department_id', models.CharField(default='Laboratory', max_length=50)),
                ('service_line', models.CharField(default='Pathology', max_length=150)),
                ('test_code', models.CharField(blank=True, max_length=50)),
                ('test_name', models.CharField(max_length=255)),
                ('patient_uhid', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('business_date', models.DateField(db_index=True)),
                ('status', models.CharField(default='pending_batch', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accrual_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsourced_test_accruals', to='accounting.journal')),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.financialevent')),
                ('vendor_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outsourced_test_accruals', to='accounting.vendorbill')),
            ],
            options={
                'db_table': 'accounts_outsourced_test_accruals',
                'indexes': [models.Index(fields=['partner_lab', 'status', 'business_date'], name='accounts_ou_partner_969961_idx')],
            },
        ),
    ]
