# Generated by Django 5.1.15 on 2026-10-09 09:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


import hashlib
import json
from datetime import timezone as dt_timezone

GENESIS_HASH = 'GENESIS_BLOCK_NORTH_HOSPITAL'


def _digest(prev, seq, occurred_at, e):
    # Frozen copy of apps.accounting.services.audit_digest / audit_fields
    at = occurred_at.astimezone(dt_timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') if occurred_at else ''
    fields = {
        'actor_id': str(e.actor_user_id or ''), 'actor_name': e.actor_name, 'actor_role': e.actor_role,
        'module': e.module, 'action': e.action, 'entity_type': e.entity_type, 'entity_id': e.entity_id,
        'reference_no': e.reference_no, 'previous_state': e.previous_state, 'new_state': e.new_state,
        'diff': e.diff, 'reason': e.reason, 'ip_address': e.ip_address, 'user_agent': e.user_agent,
    }
    body = json.dumps({'prev': prev, 'seq': seq, 'at': at, **fields}, sort_keys=True, separators=(',', ':'), default=str)
    return hashlib.sha256(body.encode('utf-8')).hexdigest()


def seal_existing_audit_logs(apps, schema_editor):
    """Re-chain rows written before Phase 11 (their old hash skipped reason/state fields) in original order."""
    Log = apps.get_model('accounting', 'AccountAuditLog')
    prev = GENESIS_HASH
    for seq, e in enumerate(Log.objects.order_by('occurred_at', 'id'), start=1):
        digest = _digest(prev, seq, e.occurred_at, e)
        Log.objects.filter(pk=e.pk).update(sequence=seq, previous_hash=prev, entry_hash=digest)
        prev = digest


TRIGGERS = {
    'sqlite': (
        [
            "CREATE TRIGGER accounts_audit_logs_no_update BEFORE UPDATE ON accounts_audit_logs "
            "BEGIN SELECT RAISE(ABORT, 'accounts_audit_logs is append-only: UPDATE denied'); END;",
            "CREATE TRIGGER accounts_audit_logs_no_delete BEFORE DELETE ON accounts_audit_logs "
            "BEGIN SELECT RAISE(ABORT, 'accounts_audit_logs is append-only: DELETE denied'); END;",
        ],
        [
            'DROP TRIGGER IF EXISTS accounts_audit_logs_no_update;',
            'DROP TRIGGER IF EXISTS accounts_audit_logs_no_delete;',
        ],
    ),
    'postgresql': (
        [
            "CREATE OR REPLACE FUNCTION accounts_audit_logs_append_only() RETURNS trigger AS $$ "
            "BEGIN RAISE EXCEPTION 'accounts_audit_logs is append-only: % denied', TG_OP; END; $$ LANGUAGE plpgsql;",
            'CREATE TRIGGER accounts_audit_logs_no_update BEFORE UPDATE OR DELETE ON accounts_audit_logs '
            'FOR EACH ROW EXECUTE FUNCTION accounts_audit_logs_append_only();',
            'CREATE TRIGGER accounts_audit_logs_no_truncate BEFORE TRUNCATE ON accounts_audit_logs '
            'FOR EACH STATEMENT EXECUTE FUNCTION accounts_audit_logs_append_only();',
        ],
        [
            'DROP TRIGGER IF EXISTS accounts_audit_logs_no_update ON accounts_audit_logs;',
            'DROP TRIGGER IF EXISTS accounts_audit_logs_no_truncate ON accounts_audit_logs;',
            'DROP FUNCTION IF EXISTS accounts_audit_logs_append_only();',
        ],
    ),
}


def _run(schema_editor, index):
    sql = TRIGGERS.get(schema_editor.connection.vendor)
    if not sql:
        return  # other engines: application-level guard in AccountAuditLog.save/delete still applies
    for statement in sql[index]:
        schema_editor.execute(statement)


def create_append_only_triggers(apps, schema_editor):
    _run(schema_editor, 0)


def drop_append_only_triggers(apps, schema_editor):
    _run(schema_editor, 1)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_lab_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditWormExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_date', models.DateField(unique=True)),
                ('from_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('to_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=500)),
                ('file_sha256', models.CharField(max_length=64)),
                ('previous_export_sha256', models.CharField(blank=True, max_length=64)),
                ('chain_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_audit_worm_exports',
                'ordering': ['-export_date'],
            },
        ),
        migrations.CreateModel(
            name='ControlDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('severity_default', models.CharField(default='High', max_length=20)),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_count', models.IntegerField(default=0)),
                ('last_violation_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts_control_definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=50, unique=True)),
                ('retain_years', models.IntegerField(default=8)),
                ('basis', models.CharField(blank=True, max_length=255)),
                ('purge_allowed', models.BooleanField(default=False)),
                ('legal_hold', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'accounts_retention_policies',
                'ordering': ['record_type'],
            },
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='sequence',
            field=models.PositiveBigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_audit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountauditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountauditlog',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='AuditEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_no', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(default='statutory', max_length=20)),
                ('auditor_firm', models.CharField(max_length=150)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('fieldwork_from', models.DateField()),
                ('fieldwork_to', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_audit_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_audit_engagements',
            },
        ),
        migrations.AddField(
            model_name='auditrequest',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='accounting.auditengagement'),
        ),
        migrations.CreateModel(
            name='AuditorAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_grants', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='accounting.auditengagement')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_auditor_grants', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_auditor_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_auditor_access_grants',
                'indexes': [models.Index(fields=['auditor', 'valid_until'], name='accounts_au_auditor_8fcd52_idx')],
            },
        ),
        migrations.RunPython(seal_existing_audit_logs, migrations.RunPython.noop),
        migrations.RunPython(create_append_only_triggers, drop_append_only_triggers),
    ]
