# Generated by Django 5.1.15 on 2026-09-16 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('procedure_name', models.CharField(max_length=200)),
                ('ot_room', models.CharField(default='OT-1', max_length=50)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('POST_OP_RECOVERY', 'Post-Op Recovery'), ('TRANSFERRED_TO_IPD', 'Transferred to IPD'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=50)),
                ('pre_op_diagnosis', models.TextField(blank=True, null=True)),
                ('post_op_notes', models.TextField(blank=True, null=True)),
                ('equipment_used', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
                ('primary_surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'surgery_bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
