# Generated by Django 5.1.15 on 2026-09-16 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('appointment_date', models.CharField(max_length=20)),
                ('slot_start_time', models.CharField(default='09:00:00', max_length=20)),
                ('slot_end_time', models.CharField(default='09:15:00', max_length=20)),
                ('token_number', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('WALK_IN', 'Walk In'), ('ONLINE', 'Online'), ('FOLLOW_UP', 'Follow Up'), ('EMERGENCY', 'Emergency')], default='WALK_IN', max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('TRIAGED', 'Triaged'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'token_number'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolic_bp', models.IntegerField(default=120)),
                ('diastolic_bp', models.IntegerField(default=80)),
                ('pulse_rate', models.IntegerField(default=72)),
                ('temperature', models.DecimalField(decimal_places=1, default=98.6, max_digits=5)),
                ('spo2', models.IntegerField(default=98)),
                ('height_cm', models.DecimalField(decimal_places=1, default=170.0, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=70.0, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=1, default=24.2, max_digits=4)),
                ('triage_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vital_signs',
            },
        ),
    ]
