# Generated by Django 5.1.15 on 2026-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='corporate_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='settlement_mode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='token_slip_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tpa_claim_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('OT', 'OT'), ('LAB', 'LAB'), ('PACKAGE', 'PACKAGE'), ('PHARMACY', 'Pharmacy')], default='OPD', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('INSURANCE_PENDING', 'Insurance Pending'), ('CORPORATE_PENDING', 'Corporate Pending'), ('CREDIT_AUTHORIZED', 'Credit Authorized')], default='UNPAID', max_length=30),
        ),
    ]
