# Generated by Django 5.1.15 on 2026-10-03 08:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_corporate_reference_invoice_settlement_mode_and_more'),
        ('ipd', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('station_location', models.CharField(choices=[('OPD_LOBBY', 'Main OPD Lobby'), ('EMERGENCY', 'Emergency & Trauma Desk'), ('IPD_DESK', 'Inpatient & Discharge Lounge'), ('DIAGNOSTICS', 'Diagnostics & Lab Billing'), ('PHARMACY', 'Pharmacy Cash Counter')], default='OPD_LOBBY', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_terminal_binding', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_counters',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(default='CORPORATE', max_length=30)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12)),
                ('utilized_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('co_pay_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('deductible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('room_rent_ceiling', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corporate_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('department', models.CharField(default='SURGERY', max_length=50)),
                ('inclusions_description', models.TextField(blank=True, default='')),
                ('exclusions_description', models.TextField(blank=True, default='')),
                ('validity_days', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TariffMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(default='GENERAL', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('emergency_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tariff_masters',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='encounter_type',
            field=models.CharField(default='OPD', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='department',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='auth_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='SUCCESS', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='tender_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit / Debit Card'), ('UPI', 'UPI / QR'), ('NETBANKING', 'Netbanking'), ('CHEQUE', 'Cheque'), ('DEPOSIT_DEDUCTION', 'Advance Deposit Deduction'), ('INSURANCE_TPA', 'Insurance / TPA Cashless'), ('CORPORATE_CREDIT', 'Corporate Credit Sponsorship')], default='CASH', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_vpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='advance_deducted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('OT', 'OT'), ('LAB', 'LAB'), ('PACKAGE', 'PACKAGE'), ('PHARMACY', 'Pharmacy'), ('EMERGENCY', 'Emergency'), ('RADIOLOGY', 'Radiology'), ('GENERAL', 'General')], default='OPD', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('INSURANCE_PENDING', 'Insurance Pending'), ('CORPORATE_PENDING', 'Corporate Pending'), ('CREDIT_AUTHORIZED', 'Credit Authorized'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.billingcounter'),
        ),
        migrations.AddField(
            model_name='payment',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.billingcounter'),
        ),
        migrations.CreateModel(
            name='CounterShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opening_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING_APPROVAL', 'Pending Supervisor Approval'), ('CLOSED', 'Closed & Reconciled')], default='OPEN', max_length=30)),
                ('denominations_submitted', models.JSONField(blank=True, default=dict)),
                ('card_settlement_batch_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('upi_settlement_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('physical_cash_count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('system_expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance_note', models.TextField(blank=True, default='')),
                ('supervisor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_shifts', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='billing.billingcounter')),
                ('supervisor_sign_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_billing_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_counter_shifts',
                'ordering': ['-opening_time'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.countershift'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.countershift'),
        ),
        migrations.CreateModel(
            name='FinancialDischargeClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clearance_status', models.CharField(choices=[('PENDING_SETTLEMENT', 'Pending Settlement'), ('DISPUTED', 'Disputed / Under Audit'), ('CLEARED', 'Financial Discharge Cleared')], default='PENDING_SETTLEMENT', max_length=30)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_covered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('patient_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('qr_verification_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_clearance', to='ipd.inpatientadmission')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_discharges', to=settings.AUTH_USER_MODEL)),
                ('final_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_clearances', to='billing.invoice')),
            ],
            options={
                'db_table': 'financial_discharge_clearances',
            },
        ),
        migrations.CreateModel(
            name='PatientDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tender_mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit / Debit Card'), ('UPI', 'UPI / QR'), ('NETBANKING', 'Netbanking'), ('CHEQUE', 'Cheque'), ('DEPOSIT_DEDUCTION', 'Advance Deposit Deduction'), ('INSURANCE_TPA', 'Insurance / TPA Cashless'), ('CORPORATE_CREDIT', 'Corporate Credit Sponsorship')], default='CASH', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Available'), ('PARTIALLY_UTILIZED', 'Partially Utilized'), ('EXHAUSTED', 'Fully Exhausted'), ('REFUNDED', 'Refunded')], default='ACTIVE', max_length=30)),
                ('receipt_printed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingcounter')),
                ('ipd_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='ipd.inpatientadmission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('clinical_justification', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Supervisor Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed / Credit Note Issued')], default='PENDING', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_tender', models.CharField(blank=True, max_length=30, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('credit_note_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='billing.payment')),
            ],
            options={
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
