# Generated by Django 5.1.15 on 2026-10-05 07:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingcounter_corporateaccount_servicepackage_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillableChargeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(default='GENERAL', max_length=50)),
                ('service_code', models.CharField(blank=True, default='', max_length=50)),
                ('service_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('source_reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billable_charges', to='patients.patient')),
            ],
            options={
                'db_table': 'billing_charge_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('receipt_type', models.CharField(choices=[('THERMAL_80MM', '80mm Thermal Slip'), ('A4_TAX_INVOICE', 'A4 Formal Tax Invoice')], default='A4_TAX_INVOICE', max_length=30)),
                ('token_slip_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('qr_verification_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('pdf_generated_path', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='billing.invoice')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_receipts', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='billing.payment')),
            ],
            options={
                'db_table': 'billing_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='billing.invoice')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='patients.patient')),
                ('refund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.refundrequest')),
            ],
            options={
                'db_table': 'billing_credit_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
