# Generated by Django 5.1.15 on 2026-10-05 07:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billablechargeitem_billingreceipt_creditnote'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGatingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(db_index=True, max_length=50)),
                ('gating_action', models.CharField(choices=[('LAB_SAMPLE_COLLECTION', 'Lab Sample Collection'), ('PHARMACY_MEDICINE_RELEASE', 'Pharmacy Medicine Release'), ('IPD_DISCHARGE_EXIT', 'IPD Discharge Exit'), ('CONSULTATION_ENTRY', 'Consultation Entry')], db_index=True, max_length=60, unique=True)),
                ('is_hard_gate', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_department_gating_rules',
                'ordering': ['department', 'gating_action'],
            },
        ),
        migrations.AddField(
            model_name='billablechargeitem',
            name='priority',
            field=models.CharField(db_index=True, default='ROUTINE', max_length=20),
        ),
        migrations.CreateModel(
            name='DepartmentChargeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('source_department', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('OT', 'OT'), ('LAB', 'LAB'), ('PACKAGE', 'PACKAGE'), ('PHARMACY', 'Pharmacy'), ('EMERGENCY', 'Emergency'), ('RADIOLOGY', 'Radiology'), ('GENERAL', 'General')], db_index=True, default='OPD', max_length=50)),
                ('encounter_type', models.CharField(default='OPD', max_length=50)),
                ('encounter_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tariff_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('service_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('override_allowed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_events', to='billing.billablechargeitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_charge_events', to='patients.patient')),
            ],
            options={
                'db_table': 'billing_department_charge_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
