# Generated by Django 5.1.15 on 2026-10-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_supervisorapprovalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('INSURANCE_PENDING', 'Insurance Pending'), ('CORPORATE_PENDING', 'Corporate Pending'), ('CREDIT_AUTHORIZED', 'Credit Authorized'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=30),
        ),
    ]
