# Generated by Django 5.1.15 on 2026-10-06 10:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_draft_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countershift',
            name='card_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='countershift',
            name='closed_with_variance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countershift',
            name='closing_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countershift',
            name='investigation_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='countershift',
            name='supervisor_finding',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='countershift',
            name='system_expected_card',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='countershift',
            name='system_expected_upi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='countershift',
            name='upi_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='countershift',
            name='variance_status',
            field=models.CharField(blank=True, choices=[('GREEN_MATCH', 'Matched'), ('RED_VARIANCE', 'Variance')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patientdeposit',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='billing.countershift'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='disbursed_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_refunds', to='billing.countershift'),
        ),
        migrations.AlterField(
            model_name='countershift',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING_APPROVAL', 'Pending Supervisor Approval'), ('UNDER_INVESTIGATION', 'Variance Under Investigation'), ('CLOSED', 'Closed & Reconciled')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='CashPickupVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(choices=[('THRESHOLD_LIMIT_EXCEEDED', 'Drawer Threshold Exceeded'), ('ROUTINE_SWEEP', 'Routine Sweep')], default='THRESHOLD_LIMIT_EXCEEDED', max_length=30)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested by Cashier'), ('COMPLETED', 'Collected by Supervisor')], default='REQUESTED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pickups', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='billing.countershift')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_cash_pickup_vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handover_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('total_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_handovers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_vault_handovers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='countershift',
            name='vault_handover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='billing.vaulthandover'),
        ),
        migrations.CreateModel(
            name='CashDenominationTally',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tally_type', models.CharField(choices=[('OPENING_FLOAT', 'Opening Float'), ('CLOSING_COUNT', 'Closing Count')], max_length=20)),
                ('count_2000', models.PositiveIntegerField(default=0)),
                ('count_500', models.PositiveIntegerField(default=0)),
                ('count_200', models.PositiveIntegerField(default=0)),
                ('count_100', models.PositiveIntegerField(default=0)),
                ('count_50', models.PositiveIntegerField(default=0)),
                ('count_20', models.PositiveIntegerField(default=0)),
                ('count_10', models.PositiveIntegerField(default=0)),
                ('coins_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_tallies', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallies', to='billing.countershift')),
            ],
            options={
                'db_table': 'billing_cash_denomination_tallies',
                'ordering': ['recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'tally_type'), name='uniq_tally_per_shift_type')],
            },
        ),
    ]
