# Generated by Django 5.1.15 on 2026-10-06 11:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_counter_shift_cash_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='assisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdeposit',
            name='assisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='assisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='escalation_reason',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='original_tender',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='refund_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='requested_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_refunds', to='billing.countershift'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='billing.billingcounter'),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='escalation_reason',
            field=models.CharField(blank=True, choices=[('SELF_RAISED', 'Raised by a supervisor (self-approval block)'), ('ABOVE_LIMIT', 'Above supervisor limit'), ('SLA_BREACH', 'Unreviewed past SLA'), ('MANUAL', 'Escalated by supervisor')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='requested_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='billing.countershift'),
        ),
        migrations.AddField(
            model_name='supervisorapprovalrequest',
            name='sla_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Supervisor Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated to Billing Admin'), ('DISBURSED', 'Disbursed / Credit Note Issued')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='supervisorapprovalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated to Billing Admin')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='BillingAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('HIGH_VALUE_CASH', 'High-value cash receipt'), ('DISCOUNT_REQUESTED', 'Discount requested'), ('VOID_REQUESTED', 'Void requested'), ('APPROVAL_DECIDED', 'Approval decided'), ('APPROVAL_ESCALATED', 'Approval escalated'), ('INVOICE_VOIDED', 'Invoice voided'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_DECIDED', 'Refund decided'), ('REFUND_PAID', 'Refund paid'), ('COUNTER_MODE', 'Counter mode'), ('CASH_PICKUP', 'Cash pickup'), ('CLOSING', 'Counter closing'), ('VAULT_HANDOVER', 'Vault handover')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='LOW', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_audit_events', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='billing.billingcounter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_billing_events', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='billing.countershift')),
            ],
            options={
                'db_table': 'billing_audit_events',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
