# Generated by Django 5.1.15 on 2026-10-06 12:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def retire_inactive_packages(apps, schema_editor):
    ServicePackage = apps.get_model('billing', 'ServicePackage')
    ServicePackage.objects.filter(is_active=False).update(status='RETIRED')


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_supervisor_governance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='length_of_stay_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='overrun_rule',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='tariffmaster',
            name='owner_department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingauditevent',
            name='event_type',
            field=models.CharField(choices=[('HIGH_VALUE_CASH', 'High-value cash receipt'), ('DISCOUNT_REQUESTED', 'Discount requested'), ('VOID_REQUESTED', 'Void requested'), ('APPROVAL_DECIDED', 'Approval decided'), ('APPROVAL_ESCALATED', 'Approval escalated'), ('INVOICE_VOIDED', 'Invoice voided'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_DECIDED', 'Refund decided'), ('REFUND_PAID', 'Refund paid'), ('COUNTER_MODE', 'Counter mode'), ('CASH_PICKUP', 'Cash pickup'), ('CLOSING', 'Counter closing'), ('VAULT_HANDOVER', 'Vault handover'), ('TARIFF_CHANGE', 'Tariff change'), ('PACKAGE_CHANGE', 'Package change')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='EmergencyMarkupSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Night surcharge', max_length=100)),
                ('department', models.CharField(db_index=True, default='ALL', max_length=50)),
                ('markup_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_from_time', models.TimeField()),
                ('applies_to_time', models.TimeField()),
                ('is_weekend_active', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markup_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_emergency_markup_schedules',
                'ordering': ['department', 'applies_from_time'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclusionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inclusion_type', models.CharField(choices=[('INCLUDED', 'Included'), ('EXCLUDED', 'Excluded · billed separately')], default='INCLUDED', max_length=10)),
                ('service_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('service_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('max_quantity_covered', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.servicepackage')),
            ],
            options={
                'db_table': 'billing_package_inclusion_items',
                'ordering': ['inclusion_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TariffChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('service_code', models.CharField(db_index=True, max_length=50)),
                ('service_name', models.CharField(max_length=200)),
                ('department', models.CharField(default='GENERAL', max_length=50)),
                ('owner_department', models.CharField(blank=True, default='', max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proposed_emergency_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_from', models.DateField()),
                ('justification', models.TextField()),
                ('impact_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved · scheduled'), ('PUBLISHED', 'Published'), ('REJECTED', 'Returned'), ('REVISION', 'Revision requested')], db_index=True, default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('cfo_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_tariff_changes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_change_requests', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='billing.tariffmaster')),
            ],
            options={
                'db_table': 'billing_tariff_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffRevisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('CHANGE_REQUEST', 'Department change request'), ('DIRECT_EDIT', 'Billing admin edit'), ('BATCH_IMPORT', 'Batch import'), ('NEW_SERVICE', 'New service')], max_length=20)),
                ('old_base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('old_emergency_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_emergency_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('applied_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('justification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='billing.tariffchangerequest')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_revisions', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='billing.tariffmaster')),
            ],
            options={
                'db_table': 'billing_tariff_revision_logs',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.RunPython(retire_inactive_packages, migrations.RunPython.noop),
    ]
