# Generated by Django 5.1.15 on 2026-10-07 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_tariff_pricing_governance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('rule_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('DISCOUNT', 'Discount Governance'), ('REFUND', 'Refund Governance'), ('CASH_DRAWER', 'Cash Drawer Limits'), ('DISCHARGE', 'Financial Discharge'), ('GENERAL', 'General Financial Policy')], db_index=True, default='GENERAL', max_length=30)),
                ('parameter_value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_policy_rules',
                'ordering': ['priority', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalMatrixTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier_level', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager'), ('ADMIN', 'Billing Admin'), ('CFO', 'CFO')], db_index=True, max_length=20)),
                ('action_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('REFUND', 'Refund'), ('VOID', 'Void'), ('WRITE_OFF', 'Write-off'), ('CREDIT_DISCHARGE', 'Credit Discharge'), ('CORPORATE_OVERRIDE', 'Corporate Override')], db_index=True, max_length=30)),
                ('max_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sla_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_approval_matrix_tiers',
                'ordering': ['action_type', 'tier_level'],
                'unique_together': {('tier_level', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='CounterHardwareRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('mac_address', models.CharField(blank=True, default='', max_length=50)),
                ('thermal_printer_name', models.CharField(blank=True, default='', max_length=100)),
                ('pos_terminal_tid', models.CharField(blank=True, default='', max_length=50)),
                ('upi_vpa', models.CharField(blank=True, default='', max_length=100)),
                ('is_terminal_lock_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='ONLINE', max_length=20)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_registry', to='billing.billingcounter')),
            ],
            options={
                'db_table': 'billing_counter_hardware_registry',
                'ordering': ['counter__code'],
            },
        ),
        migrations.CreateModel(
            name='BillingStaffRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roster_date', models.DateField(db_index=True)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning (08:00 - 16:00)'), ('EVENING', 'Evening (16:00 - 00:00)'), ('NIGHT', 'Night (00:00 - 08:00)')], default='MORNING', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed'), ('ABSENT', 'Absent')], default='SCHEDULED', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roster_shifts', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_assignments', to='billing.billingcounter')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_roster_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_staff_rosters',
                'ordering': ['roster_date', 'shift_type', 'counter__code'],
                'unique_together': {('counter', 'roster_date', 'shift_type')},
            },
        ),
    ]
