# Generated by Django 5.1.15 on 2026-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_billingpolicyrule_approvalmatrixtier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingauditevent',
            name='event_type',
            field=models.CharField(choices=[('HIGH_VALUE_CASH', 'High-value cash receipt'), ('DISCOUNT_REQUESTED', 'Discount requested'), ('VOID_REQUESTED', 'Void requested'), ('APPROVAL_DECIDED', 'Approval decided'), ('APPROVAL_ESCALATED', 'Approval escalated'), ('INVOICE_VOIDED', 'Invoice voided'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_DECIDED', 'Refund decided'), ('REFUND_PAID', 'Refund paid'), ('COUNTER_MODE', 'Counter mode'), ('CASH_PICKUP', 'Cash pickup'), ('CLOSING', 'Counter closing'), ('VAULT_HANDOVER', 'Vault handover'), ('TARIFF_CHANGE', 'Tariff change'), ('PACKAGE_CHANGE', 'Package change'), ('ROSTER_PUBLISHED', 'Roster published'), ('POLICY_CHANGE', 'Policy change'), ('MATRIX_CHANGE', 'Matrix change'), ('HARDWARE_LOCK', 'Hardware lock')], db_index=True, max_length=30),
        ),
    ]
