# Generated by Django 5.1.15 on 2026-10-07 05:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_billingauditevent_event_type'),
        ('ipd', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateaccount',
            name='billing_cycle',
            field=models.CharField(blank=True, default='Monthly · 30-day credit', max_length=100),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='contract_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='covered_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='plans_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='required_docs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='settlement_tat_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='signatories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='corporateaccount',
            name='tariff_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='billingauditevent',
            name='event_type',
            field=models.CharField(choices=[('HIGH_VALUE_CASH', 'High-value cash receipt'), ('DISCOUNT_REQUESTED', 'Discount requested'), ('VOID_REQUESTED', 'Void requested'), ('APPROVAL_DECIDED', 'Approval decided'), ('APPROVAL_ESCALATED', 'Approval escalated'), ('INVOICE_VOIDED', 'Invoice voided'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_DECIDED', 'Refund decided'), ('REFUND_PAID', 'Refund paid'), ('COUNTER_MODE', 'Counter mode'), ('CASH_PICKUP', 'Cash pickup'), ('CLOSING', 'Counter closing'), ('VAULT_HANDOVER', 'Vault handover'), ('TARIFF_CHANGE', 'Tariff change'), ('PACKAGE_CHANGE', 'Package change'), ('ROSTER_PUBLISHED', 'Roster published'), ('POLICY_CHANGE', 'Policy change'), ('MATRIX_CHANGE', 'Matrix change'), ('HARDWARE_LOCK', 'Hardware lock'), ('GOP_APPROVED', 'GOP approved'), ('CLAIM_DENIED', 'Claim denied'), ('VOUCHER_VERIFIED', 'Voucher verified'), ('CREDIT_CAP_BLOCKED', 'Credit cap blocked')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='CorporateCreditVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('employee_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(blank=True, default='', max_length=150)),
                ('relationship', models.CharField(default='SELF', max_length=50)),
                ('approved_credit_ceiling', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('validity_date', models.DateField()),
                ('is_verified', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_vouchers', to='billing.corporateaccount')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_vouchers', to='patients.patient')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_corporate_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporate_credit_vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TPAClaimRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('policy_number', models.CharField(max_length=100)),
                ('tpa_member_id', models.CharField(max_length=100)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pre_auth_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('enhancement_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pre_auth_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('QUERY_RAISED', 'Query Raised'), ('REJECTED', 'Rejected'), ('PARTIAL', 'Partially Approved')], default='PENDING', max_length=30)),
                ('gop_letter_number', models.CharField(blank=True, default='', max_length=100)),
                ('non_medical_deductibles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('copay_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('room_rent_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claim_status', models.CharField(choices=[('PRE_AUTH', 'Pre-Auth'), ('CLAIM_FILED', 'Claim Filed'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled'), ('DENIED', 'Denied')], default='PRE_AUTH', max_length=30)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('denial_reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='IPD', max_length=100)),
                ('plan_name', models.CharField(blank=True, default='', max_length=100)),
                ('dossier_data', models.JSONField(blank=True, default=dict)),
                ('tracking_notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpa_claims', to='ipd.inpatientadmission')),
                ('corporate_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpa_claims', to='billing.corporateaccount')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpa_claims', to='patients.patient')),
            ],
            options={
                'db_table': 'tpa_claim_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
