# Generated by Django 5.1.15 on 2026-10-07 07:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_corporateaccount_billing_cycle_and_more'),
        ('ipd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdischargeclearance',
            name='checklist_confirmed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='financialdischargeclearance',
            name='override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='billingauditevent',
            name='event_type',
            field=models.CharField(choices=[('HIGH_VALUE_CASH', 'High-value cash receipt'), ('DISCOUNT_REQUESTED', 'Discount requested'), ('VOID_REQUESTED', 'Void requested'), ('APPROVAL_DECIDED', 'Approval decided'), ('APPROVAL_ESCALATED', 'Approval escalated'), ('INVOICE_VOIDED', 'Invoice voided'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_DECIDED', 'Refund decided'), ('REFUND_PAID', 'Refund paid'), ('COUNTER_MODE', 'Counter mode'), ('CASH_PICKUP', 'Cash pickup'), ('CLOSING', 'Counter closing'), ('VAULT_HANDOVER', 'Vault handover'), ('TARIFF_CHANGE', 'Tariff change'), ('PACKAGE_CHANGE', 'Package change'), ('ROSTER_PUBLISHED', 'Roster published'), ('POLICY_CHANGE', 'Policy change'), ('MATRIX_CHANGE', 'Matrix change'), ('HARDWARE_LOCK', 'Hardware lock'), ('GOP_APPROVED', 'GOP approved'), ('CLAIM_DENIED', 'Claim denied'), ('VOUCHER_VERIFIED', 'Voucher verified'), ('CREDIT_CAP_BLOCKED', 'Credit cap blocked'), ('DAILY_TARIFF_ACCRUED', 'Daily tariff accrued'), ('INTERIM_DEMAND_ISSUED', 'Interim demand issued'), ('DISCHARGE_CLEARED', 'Discharge cleared'), ('DISCHARGE_GATE_VERIFIED', 'Discharge gate pass verified')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='financialdischargeclearance',
            name='clearance_status',
            field=models.CharField(choices=[('PENDING_SETTLEMENT', 'Pending Settlement'), ('DISPUTED', 'Disputed / Under Audit'), ('CLEARED', 'Financial Discharge Cleared'), ('OVERRIDDEN', 'Admin / Charity Override')], default='PENDING_SETTLEMENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='financialdischargeclearance',
            name='final_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_clearances', to='billing.invoice'),
        ),
        migrations.CreateModel(
            name='InterimDepositDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('demand_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('running_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('demanded_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Attendant Top-Up'), ('PAID', 'Settled / Deposit Received'), ('WAIVED', 'Waived / Overridden')], db_index=True, default='PENDING', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('notified_attendant', models.BooleanField(default=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_demands', to='ipd.inpatientadmission')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_interim_demands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interim_deposit_demands',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='IPDRunningLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('item_type', models.CharField(choices=[('BED_TARIFF', 'Bed Tariff'), ('NURSING_CARE', 'Nursing Care'), ('RESIDENT_ROUNDS', 'Resident Doctor Rounds'), ('OT_PROCEDURE', 'OT & Surgical Procedure'), ('LAB_TEST', 'Diagnostic Lab Test'), ('PHARMACY_ISSUE', 'Ward Pharmacy Dispense')], db_index=True, max_length=30)),
                ('service_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_interim_billed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_ledger_entries', to='ipd.inpatientadmission')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_ledger_entries', to='billing.invoiceitem')),
            ],
            options={
                'db_table': 'ipd_running_ledgers',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
