# Generated by Django 5.1.15 on 2026-10-07 07:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_financialdischargeclearance_checklist_confirmed_and_more'),
        ('ipd', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingauditevent',
            name='event_type',
            field=models.CharField(choices=[('HIGH_VALUE_CASH', 'High-value cash receipt'), ('DISCOUNT_REQUESTED', 'Discount requested'), ('VOID_REQUESTED', 'Void requested'), ('APPROVAL_DECIDED', 'Approval decided'), ('APPROVAL_ESCALATED', 'Approval escalated'), ('INVOICE_VOIDED', 'Invoice voided'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_DECIDED', 'Refund decided'), ('REFUND_PAID', 'Refund paid'), ('COUNTER_MODE', 'Counter mode'), ('CASH_PICKUP', 'Cash pickup'), ('CLOSING', 'Counter closing'), ('VAULT_HANDOVER', 'Vault handover'), ('TARIFF_CHANGE', 'Tariff change'), ('PACKAGE_CHANGE', 'Package change'), ('ROSTER_PUBLISHED', 'Roster published'), ('POLICY_CHANGE', 'Policy change'), ('MATRIX_CHANGE', 'Matrix change'), ('HARDWARE_LOCK', 'Hardware lock'), ('GOP_APPROVED', 'GOP approved'), ('CLAIM_DENIED', 'Claim denied'), ('VOUCHER_VERIFIED', 'Voucher verified'), ('CREDIT_CAP_BLOCKED', 'Credit cap blocked'), ('DAILY_TARIFF_ACCRUED', 'Daily tariff accrued'), ('INTERIM_DEMAND_ISSUED', 'Interim demand issued'), ('DISCHARGE_CLEARED', 'Discharge cleared'), ('DISCHARGE_GATE_VERIFIED', 'Discharge gate pass verified'), ('REVENUE_LEAKAGE', 'Revenue leakage flagged'), ('LEAKAGE_RECOVERED', 'Leakage converted to charge'), ('LEAKAGE_DISMISSED', 'Leakage dismissed'), ('FRAUD_SIGNAL', 'Fraud risk signal detected'), ('INVESTIGATION_EVENT', 'Investigation docket event')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='FraudRiskSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('occurrences_count', models.IntegerField(default=1)),
                ('risk_score', models.IntegerField(default=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_risk_signals', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_risk_signals', to='billing.billingcounter')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_risk_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_risk_signals',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueLeakageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leakage_type', models.CharField(choices=[('UNBILLED_ORDER_24H', 'Unbilled Order > 24h'), ('DISCHARGED_NOT_BILLED', 'Discharged Not Billed > 2h'), ('MISSED_BED_DAY', 'Missed Bed Day Tariff'), ('ORPHAN_DISPENSE', 'Orphan Pharmacy Dispense'), ('UNRECONCILED_VOID', 'Unreconciled Void / Cancellation'), ('EXCESSIVE_DISCOUNT', 'Excessive / Clustered Discount'), ('EXCESSIVE_REFUND', 'Excessive Refund Pattern')], db_index=True, max_length=30)),
                ('department', models.CharField(db_index=True, default='GENERAL', max_length=50)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('risk_score', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open / Flagged'), ('INVESTIGATING', 'Under Investigation'), ('CONVERTED_TO_CHARGE', 'Converted to Charge'), ('FALSE_POSITIVE', 'Dismissed / False Positive')], db_index=True, default='OPEN', max_length=30)),
                ('source_event_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('dismissal_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leakage_alerts', to='ipd.inpatientadmission')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leakages', to=settings.AUTH_USER_MODEL)),
                ('converted_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_leakage', to='billing.billablechargeitem')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leakage_alerts', to='patients.patient')),
            ],
            options={
                'db_table': 'revenue_leakage_alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueInvestigationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open Investigation'), ('EVIDENCE_COLLECTED', 'Evidence Collected'), ('RESOLVED', 'Resolved & Findings Filed'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('findings', models.TextField(blank=True, default='')),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_cases', to=settings.AUTH_USER_MODEL)),
                ('risk_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_cases', to='billing.fraudrisksignal')),
                ('leakage_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_cases', to='billing.revenueleakagealert')),
            ],
            options={
                'db_table': 'revenue_investigation_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
