# Generated by Django 5.1.15 on 2026-10-07 09:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


import hashlib


def seal_existing_audit_events(apps, schema_editor):
    """Chain the audit rows written before Phase 11 in their original order."""
    Event = apps.get_model('billing', 'BillingAuditEvent')
    prev = ''
    for seq, e in enumerate(Event.objects.order_by('occurred_at', 'id'), start=1):
        payload = '|'.join(str(x) for x in (
            prev, seq, e.occurred_at.isoformat() if e.occurred_at else '', e.event_type, e.severity, e.title, e.detail,
            e.counter_id or '', e.shift_id or '', e.actor_id or '', e.reference))
        digest = hashlib.sha256(payload.encode('utf-8')).hexdigest()
        Event.objects.filter(pk=e.pk).update(sequence=seq, prev_hash=prev, entry_hash=digest)
        prev = digest


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_billingauditevent_event_type_fraudrisksignal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingauditevent',
            name='entry_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='billingauditevent',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='billingauditevent',
            name='sequence',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billingauditevent',
            name='event_type',
            field=models.CharField(choices=[('HIGH_VALUE_CASH', 'High-value cash receipt'), ('DISCOUNT_REQUESTED', 'Discount requested'), ('VOID_REQUESTED', 'Void requested'), ('APPROVAL_DECIDED', 'Approval decided'), ('APPROVAL_ESCALATED', 'Approval escalated'), ('INVOICE_VOIDED', 'Invoice voided'), ('REFUND_REQUESTED', 'Refund requested'), ('REFUND_DECIDED', 'Refund decided'), ('REFUND_PAID', 'Refund paid'), ('COUNTER_MODE', 'Counter mode'), ('CASH_PICKUP', 'Cash pickup'), ('CLOSING', 'Counter closing'), ('VAULT_HANDOVER', 'Vault handover'), ('TARIFF_CHANGE', 'Tariff change'), ('PACKAGE_CHANGE', 'Package change'), ('ROSTER_PUBLISHED', 'Roster published'), ('POLICY_CHANGE', 'Policy change'), ('MATRIX_CHANGE', 'Matrix change'), ('HARDWARE_LOCK', 'Hardware lock'), ('GOP_APPROVED', 'GOP approved'), ('CLAIM_DENIED', 'Claim denied'), ('VOUCHER_VERIFIED', 'Voucher verified'), ('CREDIT_CAP_BLOCKED', 'Credit cap blocked'), ('DAILY_TARIFF_ACCRUED', 'Daily tariff accrued'), ('INTERIM_DEMAND_ISSUED', 'Interim demand issued'), ('DISCHARGE_CLEARED', 'Discharge cleared'), ('DISCHARGE_GATE_VERIFIED', 'Discharge gate pass verified'), ('REVENUE_LEAKAGE', 'Revenue leakage flagged'), ('LEAKAGE_RECOVERED', 'Leakage converted to charge'), ('LEAKAGE_DISMISSED', 'Leakage dismissed'), ('FRAUD_SIGNAL', 'Fraud risk signal detected'), ('INVESTIGATION_EVENT', 'Investigation docket event'), ('PERIOD_CLOSED', 'Period closed'), ('PERIOD_REOPEN', 'Period reopen'), ('PERIOD_LOCK_DENIED', 'Entry refused in locked period'), ('REPORT_EXPORTED', 'Report exported'), ('ERP_JOURNAL', 'ERP journal posted')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='DailyRevenueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('department', models.CharField(default='ALL', max_length=50)),
                ('tender_mode', models.CharField(default='ALL', max_length=30)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxes_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_daily_revenue_snapshots',
                'ordering': ['-snapshot_date', 'department', 'tender_mode'],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'department', 'tender_mode'), name='uniq_daily_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriodLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=40)),
                ('period_type', models.CharField(choices=[('DAILY', 'Day'), ('MONTHLY', 'Month'), ('ANNUAL', 'Financial year')], max_length=10)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PRE_CLOSE_AUDIT', 'Pre-close audit'), ('LOCKED', 'Locked'), ('REOPENED', 'Reopened (time-boxed)')], db_index=True, default='OPEN', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('total_gross_billed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('carry_forward_note', models.TextField(blank=True, default='')),
                ('journal', models.JSONField(blank=True, default=list)),
                ('journal_reference', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('reopen_requested_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
                ('reopen_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_reopen_approvals', to=settings.AUTH_USER_MODEL)),
                ('reopen_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_reopen_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_financial_period_locks',
                'ordering': ['-start_date', 'period_type'],
                'constraints': [models.UniqueConstraint(fields=('period_type', 'start_date'), name='uniq_period_lock')],
            },
        ),
        migrations.RunPython(seal_existing_audit_events, migrations.RunPython.noop),
    ]
