# Generated by Django 5.1.15 on 2026-10-08 11:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_reports_period_close_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('source_type', models.CharField(choices=[('CASHIER_SETTLEMENT', 'Cashier Settlement'), ('PATIENT_DEPOSIT', 'Patient Deposit'), ('REFUND_DISBURSAL', 'Refund Disbursal'), ('PERIOD_CLOSE', 'Period Close'), ('AD_HOC', 'Ad-hoc Posting')], db_index=True, default='CASHIER_SETTLEMENT', max_length=40)),
                ('narration', models.TextField(blank=True, default='')),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_balanced', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_journal_entries', to='billing.invoice')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_gl_entries', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_journal_entries', to='billing.billingreceipt')),
            ],
            options={
                'db_table': 'billing_gl_journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(db_index=True, max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('department', models.CharField(blank=True, db_index=True, default='GENERAL', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.generalledgerjournalentry')),
            ],
            options={
                'db_table': 'billing_gl_line_items',
                'ordering': ['account_code', '-debit_amount'],
            },
        ),
    ]
