const mono="font-family:'JetBrains Mono',monospace";
const card='background:#FFFFFF;border:1px solid #E5E7EB;border-radius:12px';
const badge=(t,fg,bg)=>`<span style="font-size:12px;font-weight:500;color:{{ ${fg} }};background:{{ ${bg} }};border-radius:999px;padding:3px 10px;white-space:nowrap">{{ ${t} }}</span>`;
const chip=(t,fg,bg)=>`<span style="font-size:12px;font-weight:500;color:{{ ${fg} }};background:{{ ${bg} }};border-radius:6px;padding:2px 8px;justify-self:start;white-space:nowrap">{{ ${t} }}</span>`;
const K=(l)=>`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:16px"><sc-for list="{{ ${l} }}" as="k" hint-placeholder-count="4"><div style="${card};padding:20px;height:120px;display:flex;flex-direction:column;justify-content:space-between;box-shadow:0 1px 2px rgba(17,24,39,0.04)"><div style="display:flex;justify-content:space-between;align-items:center"><span style="font-size:13px;color:#6B7280">{{ k.label }}</span><i class="{{ k.icon }}" style="font-size:18px;color:#6B7280"></i></div><div style="${mono};font-size:24px;font-weight:600;letter-spacing:-0.02em;color:{{ k.valColor }}">{{ k.value }}</div><div style="display:flex;justify-content:space-between;gap:8px;font-size:12px"><span style="color:#6B7280;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{{ k.sub }}</span><span style="color:{{ k.trendColor }};white-space:nowrap;font-weight:500">{{ k.trend }}</span></div></div></sc-for></div>`;
const H=(t,d,act='')=>`<div style="display:flex;flex-wrap:wrap;gap:16px;align-items:flex-end;justify-content:space-between"><div style="display:flex;flex-direction:column;gap:6px"><h1 style="margin:0;font-size:32px;font-weight:700;letter-spacing:-0.01em">${t}</h1><p style="margin:0;font-size:14px;color:#6B7280;max-width:760px">${d}</p></div><div style="display:flex;gap:8px;flex-wrap:wrap">${act}</div></div>`;
const tabs=(l)=>`<div style="display:flex;gap:4px;flex-wrap:wrap;background:#F3F4F6;border-radius:10px;padding:4px;align-self:flex-start"><sc-for list="{{ ${l} }}" as="t" hint-placeholder-count="3"><button onClick="{{ t.pick }}" style="height:32px;padding:0 12px;border:none;border-radius:8px;background:{{ t.bg }};color:{{ t.fg }};font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap;box-shadow:{{ t.shadow }}">{{ t.label }} <span style="${mono};font-size:11px;color:#6B7280">{{ t.count }}</span></button></sc-for></div>`;
const th=(cols,labels)=>`<div style="display:grid;grid-template-columns:${cols};gap:16px;align-items:center;height:44px;padding:0 20px;background:#F9FAFB;border-bottom:1px solid #E5E7EB;font-size:12px;color:#6B7280;font-weight:500">${labels.map(l=>l.startsWith('>')?`<span style="text-align:right">${l.slice(1)}</span>`:`<span>${l}</span>`).join('')}</div>`;
const tr=(cols,list,as,cells,click='',minH=56)=>`<sc-for list="{{ ${list} }}" as="${as}" hint-placeholder-count="5"><div ${click?`onClick="{{ ${as}.${click} }}"`:''} style="display:grid;grid-template-columns:${cols};gap:16px;align-items:center;min-height:${minH}px;padding:8px 20px;border-bottom:1px solid #F3F4F6;${click?'cursor:pointer;':''}background:{{ ${as}.rowBg }}" ${click?'style-hover="background:#F5F9FF"':''}>${cells}</div></sc-for>`;
const two=(a,b)=>`<div style="display:flex;flex-direction:column;min-width:0"><span style="font-size:14px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{{ ${a} }}</span><span style="${mono};font-size:12px;color:#6B7280;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{{ ${b} }}</span></div>`;
const m=(v,extra='')=>`<span style="${mono};font-size:13px;text-align:right;${extra}">{{ ${v} }}</span>`;
const txt=(v,extra='')=>`<span style="font-size:13px;${extra}">{{ ${v} }}</span>`;
const wrap=(inner,minw)=>`<div style="overflow-x:auto"><div style="min-width:${minw}px">${inner}</div></div>`;
const cardHead=(title,sub,right='')=>`<div style="display:flex;flex-wrap:wrap;gap:12px;align-items:center;justify-content:space-between;padding:16px 20px;border-bottom:1px solid #E5E7EB"><div style="display:flex;flex-direction:column;gap:2px"><span style="font-size:16px;font-weight:600">${title}</span>${sub?`<span style="font-size:13px;color:#6B7280">${sub}</span>`:''}</div>${right}</div>`;
const box=(inner,extra='')=>`<div style="${card};overflow:hidden;${extra}">${inner}</div>`;
const btn1=(lbl,on,i='')=>`<button onClick="{{ ${on} }}" style="height:40px;padding:0 16px;white-space:nowrap;border:none;background:#2563EB;color:#FFFFFF;border-radius:10px;font-size:14px;font-weight:500;cursor:pointer;display:flex;align-items:center;gap:8px">${i?`<i class="${i}" style="font-size:16px"></i>`:''}${lbl}</button>`;
const btn2=(lbl,on,i='')=>`<button onClick="{{ ${on} }}" style="height:40px;padding:0 16px;white-space:nowrap;border:1px solid #E5E7EB;background:#FFFFFF;color:#111827;border-radius:10px;font-size:14px;font-weight:500;cursor:pointer;display:flex;align-items:center;gap:8px" style-hover="background:#F9FAFB">${i?`<i class="${i}" style="font-size:16px"></i>`:''}${lbl}</button>`;
const sbtn=(lbl,on,fg='#111827',bd='#E5E7EB',bg='#FFFFFF')=>`<button onClick="{{ ${on} }}" style="height:32px;padding:0 12px;border:1px solid ${bd};background:${bg};color:${fg};border-radius:8px;font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap">${lbl}</button>`;
const acts=(list)=>`<div style="display:flex;gap:12px;justify-content:flex-end;flex-wrap:wrap"><sc-for list="{{ ${list} }}" as="x" hint-placeholder-count="1"><button onClick="{{ x.run }}" style="border:none;background:transparent;padding:0;color:{{ x.color }};font-size:13px;font-weight:500;cursor:pointer;white-space:nowrap">{{ x.label }}</button></sc-for></div>`;
const bar=(w,c)=>`<div style="height:6px;border-radius:999px;background:#F3F4F6;overflow:hidden"><div style="height:100%;width:{{ ${w} }}%;background:{{ ${c} }}"></div></div>`;
const drawer=(cond,title,sub,body,foot)=>`
<sc-if value="{{ ${cond} }}" hint-placeholder-val="{{ false }}">
  <div style="position:fixed;inset:0;z-index:20;display:flex;justify-content:flex-end">
    <div onClick="{{ closeDrawer }}" style="position:absolute;inset:0;background:rgba(17,24,39,0.24);animation:fadeIn 0.15s ease"></div>
    <div style="position:relative;width:560px;max-width:100%;height:100%;background:#FFFFFF;border-left:1px solid #E5E7EB;box-shadow:-8px 0 32px rgba(17,24,39,0.08);display:flex;flex-direction:column;animation:slideIn 0.2s ease">
      <div style="display:flex;justify-content:space-between;align-items:flex-start;padding:20px 24px;border-bottom:1px solid #E5E7EB"><div style="display:flex;flex-direction:column;gap:4px"><span style="font-size:20px;font-weight:600">${title}</span><span style="font-size:13px;color:#6B7280">${sub}</span></div><button onClick="{{ closeDrawer }}" style="width:36px;height:36px;border:none;background:transparent;border-radius:10px;cursor:pointer;color:#6B7280"><i class="icon-x" style="font-size:18px"></i></button></div>
      <div style="flex:1;overflow-y:auto;padding:24px;display:flex;flex-direction:column;gap:20px">${body}</div>
      <div style="display:flex;gap:8px;justify-content:flex-end;align-items:center;flex-wrap:wrap;padding:16px 24px;border-top:1px solid #E5E7EB">${foot}</div>
    </div>
  </div>
</sc-if>`;
const kv=(l,v)=>`<div style="display:flex;flex-direction:column;gap:2px;min-width:0"><span style="font-size:12px;color:#6B7280">${l}</span><span style="font-size:14px">${v}</span></div>`;
const field=(label,v,on,ph='',m2=false)=>`<label style="display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:500">${label}<input value="{{ ${v} }}" onChange="{{ ${on} }}" placeholder="${ph}" style="height:40px;border:1px solid #E5E7EB;border-radius:10px;padding:0 12px;font-size:14px;${m2?mono+';':''}outline:none" style-focus="border-color:#2563EB"></label>`;
const insert=(h,{tpl,js,ret,drawers})=>{
  if(tpl){const i=h.indexOf('\n  </main>');if(i<0)throw new Error('main');h=h.slice(0,i)+'\n'+tpl+h.slice(i);}
  if(drawers){const k='\n<sc-if value="{{ hasToast }}"';const i=h.lastIndexOf(k);if(i<0)throw new Error('toast');h=h.slice(0,i)+drawers+h.slice(i);}
  if(js){const i=h.indexOf('    // ---------- nav');if(i<0)throw new Error('navjs');h=h.slice(0,i)+js+'\n'+h.slice(i);}
  if(ret){const k='      closeDrawer: () => this.setState({ drawer: null }),';const i=h.indexOf(k);if(i<0)throw new Error('ret');h=h.slice(0,i)+ret+'\n'+h.slice(i);}
  return h;};
return {mono,card,badge,chip,K,H,tabs,th,tr,two,m,txt,wrap,cardHead,box,btn1,btn2,sbtn,acts,bar,drawer,kv,field,insert};
