# Generated by Django 5.1.15 on 2026-10-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HOSPITAL_ADMIN', 'Hospital Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('RECEPTIONIST', 'Receptionist'), ('RECEPTION_SUPERVISOR', 'Reception Supervisor'), ('DOCTOR', 'Doctor'), ('DOCTOR_ASSISTANT', 'Doctor Assistant'), ('NURSE', 'Nurse'), ('LAB_TECH', 'Lab Technician'), ('PATHOLOGIST', 'Pathologist'), ('SURGEON', 'Surgeon'), ('ANESTHETIST', 'Anesthetist'), ('OT_MANAGER', 'OT Manager'), ('WARD_MANAGER', 'Ward Manager'), ('PHARMACIST', 'Pharmacist'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('CASHIER', 'Cashier'), ('BILLING_SUPERVISOR', 'Billing Supervisor'), ('INSURANCE_COORDINATOR', 'Insurance Coordinator'), ('PATIENT', 'Patient')], default='RECEPTIONIST', max_length=50),
        ),
    ]
