# Generated by Django 5.1.15 on 2026-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HOSPITAL_ADMIN', 'Hospital Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('RECEPTIONIST', 'Receptionist'), ('RECEPTION_SUPERVISOR', 'Reception Supervisor'), ('DOCTOR', 'Doctor'), ('DOCTOR_ASSISTANT', 'Doctor Assistant'), ('NURSE', 'Nurse'), ('LAB_TECH', 'Lab Technician'), ('PATHOLOGIST', 'Pathologist'), ('SURGEON', 'Surgeon'), ('ANESTHETIST', 'Anesthetist'), ('OT_MANAGER', 'OT Manager'), ('WARD_MANAGER', 'Ward Manager'), ('PHARMACIST', 'Pharmacist'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('CASHIER', 'Cashier'), ('BILLING_SUPERVISOR', 'Billing Supervisor'), ('BILLING_ADMIN', 'Billing Admin'), ('BILLING_MANAGER', 'Billing Manager'), ('FINANCE_MANAGER', 'Finance Manager'), ('INTERNAL_AUDITOR', 'Internal Auditor'), ('ACCOUNTS_EXECUTIVE', 'Accounts Executive'), ('ACCOUNTS_SUPERVISOR', 'Accounts Supervisor'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('FINANCE_CONTROLLER', 'Finance Controller'), ('CFO', 'Chief Financial Officer'), ('AUDITOR', 'Auditor'), ('INSURANCE_COORDINATOR', 'Insurance Coordinator'), ('PATIENT', 'Patient')], default='RECEPTIONIST', max_length=50),
        ),
    ]
