# Generated by Django 5.1.15 on 2026-09-16 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department_type', models.CharField(default='CLINICAL', max_length=50)),
                ('head_of_department', models.CharField(blank=True, max_length=100, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='North Hospital Clinical Enterprise', max_length=200)),
                ('tagline', models.CharField(default='Excellence in Tertiary Patient Care & Research', max_length=255)),
                ('email', models.EmailField(default='contact@northhospital.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 019-2834', max_length=50)),
                ('emergency_phone', models.CharField(default='+1 (555) 911-0000', max_length=50)),
                ('address', models.TextField(default='100 Medical Center Way')),
                ('city', models.CharField(default='Metropolis', max_length=100)),
                ('state', models.CharField(default='NY', max_length=100)),
                ('postal_code', models.CharField(default='10001', max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('tax_id', models.CharField(default='TX-998822-US', max_length=100)),
                ('accreditation', models.CharField(default='JCI Accredited, Level 1 Trauma Center', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_profile',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(default='GENERAL_WARD', max_length=50)),
                ('max_occupancy', models.IntegerField(default=4)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('is_clean', models.BooleanField(default=True)),
                ('is_operational', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='organization.department')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50, unique=True)),
                ('bed_type', models.CharField(default='STANDARD', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=50)),
                ('daily_tariff', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('current_patient_uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('current_patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='organization.room')),
            ],
            options={
                'db_table': 'beds',
            },
        ),
    ]
