# Generated by Django 5.1.15 on 2026-10-02 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybatch',
            name='grn_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacymedicine',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_medicines', to='pharmacy.pharmacysupplier'),
        ),
        migrations.AddField(
            model_name='pharmacymedicine',
            name='is_cold_chain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacymedicine',
            name='schedule',
            field=models.CharField(db_index=True, default='H', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacypurchaserequest',
            name='goods_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchaserequest',
            name='history_timestamps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacypurchaserequest',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacypurchaserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='pharmacy.pharmacysupplier'),
        ),
        migrations.AddField(
            model_name='pharmacypurchaserequest',
            name='workflow_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='category',
            field=models.CharField(default='General formulary', max_length=150),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='lead_time_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=95.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pharmacysupplier',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacybatch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Depleted', 'Depleted'), ('Expired', 'Expired'), ('Quarantined', 'Quarantined'), ('Return', 'Return to Supplier'), ('Write-off', 'Marked Write-off'), ('Recalled', 'Recalled')], db_index=True, default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacypurchaserequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending approval', 'Pending approval'), ('Approved', 'Approved'), ('PO issued', 'PO issued'), ('Receiving', 'Receiving'), ('Closed', 'Closed'), ('Rejected', 'Rejected'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CONVERTED_TO_PO', 'Converted to PO')], db_index=True, default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacystocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIVE_PO', 'Receive Purchase Order'), ('DISPENSE_OPD', 'Dispense OPD Prescription'), ('ISSUE_IPD', 'Issue Inpatient Ward Request'), ('SALE_OTC', 'Over-The-Counter Sale'), ('RETURN_RESTOCK', 'Return & Restock'), ('RETURN_QUARANTINE', 'Return & Quarantine'), ('AUDIT_ADJUSTMENT', 'Audit Count Adjustment'), ('EXPIRED_DISPOSAL', 'Expired Disposal'), ('TRANSFER_OUT', 'Internal Transfer Out'), ('TRANSFER_IN', 'Internal Transfer In')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PharmacyGoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('is_cold_chain', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending QC', 'Pending QC'), ('Posted', 'Posted'), ('Rejected', 'Rejected')], db_index=True, default='Pending QC', max_length=30)),
                ('qc_checks', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='pharmacy.pharmacypurchaseorder')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='pharmacy.pharmacypurchaserequest')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goods_receipts', to='pharmacy.pharmacysupplier')),
            ],
            options={
                'db_table': 'pharmacy_goods_receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyStockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending approval', 'Pending approval'), ('Posted', 'Posted'), ('Rejected', 'Rejected')], db_index=True, default='Posted', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='initiated_adjustments', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_adjustments', to='pharmacy.pharmacybatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_adjustments', to='pharmacy.pharmacymedicine')),
            ],
            options={
                'db_table': 'pharmacy_stock_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyGoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('received_quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.pharmacygoodsreceipt')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grn_items', to='pharmacy.pharmacymedicine')),
            ],
            options={
                'db_table': 'pharmacy_goods_receipt_items',
                'constraints': [models.CheckConstraint(condition=models.Q(('received_quantity__gt', 0)), name='chk_ph_grn_item_qty_gt_0'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='chk_ph_grn_item_cost_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='PharmacyTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Dispatched', 'Dispatched'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], db_index=True, default='Requested', max_length=30)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_transfers', to='pharmacy.pharmacybatch')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_transfers', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers', to='pharmacy.pharmacymedicine')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_transfer_requests',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_ph_tr_qty_gt_0')],
            },
        ),
    ]
