# Generated by Django 5.1.15 on 2026-10-02 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacy', '0002_pharmacybatch_grn_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacycontrolleddrugregister',
            name='dispense_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_register_entries', to='pharmacy.pharmacydispenseorder'),
        ),
        migrations.AlterField(
            model_name='pharmacycontrolleddrugregister',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_drug_entries', to='patients.patient'),
        ),
    ]
