# Generated by Django 5.1.15 on 2026-10-02 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacycontrolleddrugregister_dispense_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='allergy_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_overridden_dispenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='allergy_warning_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='has_allergy_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='priority',
            field=models.CharField(db_index=True, default='ROUTINE', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorderitem',
            name='allergy_conflict_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorderitem',
            name='has_allergy_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pharmacydispenseorderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_items', to='pharmacy.pharmacybatch'),
        ),
        migrations.AlterField(
            model_name='pharmacydispenseorderitem',
            name='dispensed_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
