# Generated by Django 5.1.15 on 2026-10-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacy', '0004_pharmacydispenseorder_allergy_overridden_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='controlled_drug_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='counseling_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='identity_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='interaction_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorderitem',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorderitem',
            name='substituted_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='pharmacy.pharmacymedicine'),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorderitem',
            name='substitution_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='disposition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='inspection_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='non_returnable_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='original_otc_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='pharmacy.pharmacyotcsale'),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='refund_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='status',
            field=models.CharField(db_index=True, default='Requested', max_length=30),
        ),
        migrations.AddField(
            model_name='pharmacyreturnitem',
            name='otc_sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='pharmacy.pharmacyotcsaleitem'),
        ),
        migrations.AlterField(
            model_name='pharmacyreturn',
            name='original_dispense_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='pharmacy.pharmacydispenseorder'),
        ),
        migrations.AlterField(
            model_name='pharmacyreturn',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_returns', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='pharmacyreturnitem',
            name='dispense_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='pharmacy.pharmacydispenseorderitem'),
        ),
    ]
