# Generated by Django 5.1.15 on 2026-10-02 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_pharmacydispenseorder_controlled_drug_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='corporate_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='credit_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='handover_policy',
            field=models.CharField(default='PRE_PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='insurance_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='ipd_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='receipt_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='token_slip_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PharmacyCounterShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter_name', models.CharField(default='Counter 2 · Main OPD', max_length=50)),
                ('shift_date', models.DateField(default=django.utils.timezone.now)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning (07:00 - 15:00)'), ('EVENING', 'Evening (15:00 - 23:00)'), ('NIGHT', 'Night (23:00 - 07:00)')], default='MORNING', max_length=20)),
                ('opening_float', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('upi_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refunds_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pharmacy_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_counter_shifts',
                'ordering': ['-opened_at'],
            },
        ),
    ]
