# Generated by Django 5.1.15 on 2026-10-02 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_pharmacydispenseorder_bed_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacycontrolleddrugregister',
            name='discrepancy_noted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacycontrolleddrugregister',
            name='discrepancy_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacycontrolleddrugregister',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacycontrolleddrugregister',
            name='rx_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacycontrolleddrugregister',
            name='vault_location',
            field=models.CharField(blank=True, default='Vault Safe A (Dual Key)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PharmacyVaultReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reconciliation_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('register_balance', models.IntegerField()),
                ('physical_count', models.IntegerField()),
                ('variance', models.IntegerField()),
                ('status', models.CharField(db_index=True, default='Reconciled', max_length=30)),
                ('discrepancy_reason', models.TextField(blank=True, null=True)),
                ('vault_location', models.CharField(default='Vault Safe A (Dual Key)', max_length=100)),
                ('witness_role', models.CharField(default='Head Nurse / Shift Incharge', max_length=100)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vault_reconciliations', to='pharmacy.pharmacybatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vault_reconciliations', to='pharmacy.pharmacymedicine')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='performed_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('witness_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='witnessed_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_vault_reconciliations',
                'ordering': ['-reconciled_at'],
            },
        ),
    ]
