# Generated by Django 5.1.15 on 2026-10-02 17:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacycontrolleddrugregister_discrepancy_noted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDepartmentSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=100)),
                ('value_type', models.CharField(default='BOOLEAN', max_length=20)),
                ('boolean_val', models.BooleanField(blank=True, null=True)),
                ('string_val', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_changed_by', models.CharField(default='Dr. Pooja Shah · Chief Pharmacist', max_length=150)),
                ('last_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pharmacy_department_settings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyDutySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('day_label', models.CharField(default='Today', max_length=50)),
                ('shift_slot', models.CharField(default='Morning · 07:00–15:00', max_length=100)),
                ('shift_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning (07:00 - 15:00)'), ('EVENING', 'Evening (15:00 - 23:00)'), ('NIGHT', 'Night (23:00 - 07:00)')], default='MORNING', max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('required_staff_count', models.IntegerField(default=2)),
                ('status', models.CharField(default='Covered', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ManyToManyField(blank=True, related_name='pharmacy_duty_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_duty_schedules',
                'ordering': ['shift_date', 'shift_type'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyGovernanceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_name', models.CharField(max_length=150)),
                ('terminal', models.CharField(default='OPD-C2', max_length=50)),
                ('action', models.CharField(max_length=200)),
                ('entity_reference', models.CharField(max_length=200)),
                ('severity', models.CharField(db_index=True, default='Info', max_length=30)),
                ('details', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_governance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_governance_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
