# Generated by Django 5.1.15 on 2026-10-04 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_pharmacydepartmentsetting_pharmacydutyschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='prescription_outcome',
            field=models.CharField(blank=True, choices=[('FULL_PURCHASE', 'Full Purchase'), ('PARTIAL_PURCHASE', 'Partial Purchase'), ('PURCHASED_OUTSIDE', 'Purchased Outside'), ('DECIDE_LATER', 'Decide Later')], default='FULL_PURCHASE', max_length=30),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='purchased_outside_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='purchased_outside_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outside_dispenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='purchased_outside_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorder',
            name='purchased_outside_reason',
            field=models.CharField(blank=True, choices=[('PATIENT_CHOICE', 'Patient Choice'), ('PRICE_CONCERN', 'Price Concern'), ('OUT_OF_STOCK', 'Out Of Stock'), ('INSURANCE_RESTRICTION', 'Insurance Restriction')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispenseorderitem',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pharmacydispenseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('UNDER_REVIEW', 'Under Review'), ('AWAITING_STOCK', 'Awaiting Stock'), ('VERIFIED', 'Verified'), ('DISPENSED', 'Dispensed / Fulfilled'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('PURCHASED_OUTSIDE', 'Purchased Outside'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
