# Generated by Django 5.1.15 on 2026-09-16 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ward_name', models.CharField(default='General Ward', max_length=100)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('POST_OP', 'Post-Op'), ('OBSERVATION', 'Observation'), ('DISCHARGE_INITIATED', 'Discharge Initiated'), ('DISCHARGED', 'Discharged')], default='ADMITTED', max_length=50)),
                ('admitting_diagnosis', models.TextField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
            options={
                'db_table': 'inpatient_admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('scheduled_time', models.CharField(max_length=50)),
                ('administered_time', models.DateTimeField(blank=True, null=True)),
                ('is_given', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_records', to='ipd.inpatientadmission')),
            ],
            options={
                'db_table': 'medication_administrations',
            },
        ),
    ]
