from django.urls import re_path
from .views import (
    InvoiceListCreateView, InvoiceDetailView, PaymentCreateView,
    TariffListCreateView, TariffDetailView,
    ServicePackageListCreateView, ServicePackageDetailView,
    CorporateAccountListCreateView, CorporateAccountDetailView,
    PricingQuoteCalculateView,
    CashierQueueView, MultiTenderPaymentView,
    ShiftOpenView, ShiftCurrentView, ShiftCloseView,
    InvoiceReceiptDetailView,
    BillableChargeItemListCreateView, PatientDepositListCreateView,
    PatientLedgerDetailView, RefundRequestCreateView,
    RefundApproveDisburseView, BillingReceiptListView, CreditNoteListView,
    DepartmentChargeEmitView, DepartmentChargeQueueView,
    ClinicalGatingClearanceCheckView, DepartmentChargeCancelView,
    DepartmentGatingRuleListUpdateView,
    CashierDashboardView, CashierLiveQueueView, CashierPatientWorkspaceView,
    CashierBillAndCollectView, CashierQuickWalkinView, CashierTenderCalculatorView,
    DiscountGuardCheckView, ApprovalRequestListCreateView, ApprovalRequestDecideView,
    CashierAddServiceView, CashierRemoveServiceView,
    CashierDraftCreateView, CashierDraftDiscardView, CashierDraftCollectView,
    ShiftCashPickupView, ShiftSupervisorSignoffView, ShiftSupervisorBoardView, VaultHandoverView,
    SupervisorDashboardView, SupervisorApprovalQueueView, SupervisorApprovalActionView,
    SupervisorRefundQueueView, SupervisorRefundActionView, RefundCashDisburseView,
    InvoiceVoidRequestView, SupervisorCounterModeView, SupervisorAuditStreamView, SupervisorAuditReviewView,
    TariffChangeRequestView, TariffChangeDecideView, TariffBatchImportView,
    ServicePackageLifecycleView, ServicePackageCoverageView, MarkupScheduleListCreateView, MarkupScheduleDetailView,
    BillingAdminOverviewView, BillingAdminCountersView, BillingAdminCounterDetailView,
    BillingAdminStaffRosterView, BillingAdminStaffRosterPublishView,
    BillingAdminApprovalMatrixView, BillingAdminApprovalMatrixTestRouteView,
    BillingAdminPoliciesView, BillingAdminPolicyDetailView,
    TPAClaimsListView, TPAClaimPreAuthDetailView, TPAClaimDossierView,
    TPACoPaySplitCalculateView, InsurancePayersListView,
    CorporateAccountsOverviewView, CorporateVouchersListView, CorporateVoucherVerifyView,
    IPDAdmissionsOverviewView, IPDRunningBillDetailView, IPDRunningChargeAddView,
    IPDDischargeChecklistUpdateView, IPDDailyTariffAccrualCronView, IPDInterimDemandView,
    IPDFinalBillConsolidateView, IPDDischargeClearanceIssueView, IPDDischargeClearanceVerifyView,
    RevenueIntegrityOverviewView, RevenueLeakageListView, RevenueLeakageScanView,
    RevenueLeakageConvertChargeView, RevenueLeakageDismissView, RevenueLeakageAssignView,
    FraudRiskSignalListView, FraudRiskSignalScanView, FraudRiskSignalAcknowledgeView,
    RevenueInvestigationListCreateView, RevenueInvestigationDetailUpdateView,
    ReportCatalogueView, ReportRunView, RevenueAnalyticsView, DailyCollectionsReportView, DepartmentRevenueReportView,
    TaxGstReportView, AgingReportView, CashierProductivityReportView, SettlementJournalPostView,
    LiveJournalStreamView, LiveDepartmentRevenueSummaryView,
    PeriodCloseView, PeriodCloseActionView, PeriodJournalView, BillingAuditLogView, BillingAuditChainVerifyView
)

urlpatterns = [
    # Phase 1: Core Billing Backend (Invoices, Multi-Tender, Deposits, Ledger, Receipts, Refunds)
    re_path(r'^/invoices/?$', InvoiceListCreateView.as_view(), name='invoice-list-create'),
    re_path(r'^/invoices/(?P<pk>[^/]+)/?$', InvoiceDetailView.as_view(), name='invoice-detail'),
    re_path(r'^/invoices/(?P<pk>[0-9a-f-]{36})/void-request/?$', InvoiceVoidRequestView.as_view(), name='invoice-void-request'),
    re_path(r'^/invoices/(?P<pk>[^/]+)/receipt/?$', InvoiceReceiptDetailView.as_view(), name='invoice-receipt-detail'),
    re_path(r'^/payments/?$', PaymentCreateView.as_view(), name='payment-create'),
    re_path(r'^/payments/multi-tender/?$', MultiTenderPaymentView.as_view(), name='payment-multi-tender'),
    re_path(r'^/charges/?$', BillableChargeItemListCreateView.as_view(), name='charge-list-create'),
    re_path(r'^/deposits/?$', PatientDepositListCreateView.as_view(), name='deposit-list-create'),
    re_path(r'^/patients/(?P<uhid>[^/]+)/ledger/?$', PatientLedgerDetailView.as_view(), name='patient-ledger'),
    re_path(r'^/refunds/request/?$', RefundRequestCreateView.as_view(), name='refund-request'),
    re_path(r'^/refunds/?$', RefundRequestCreateView.as_view(), name='refund-list'),
    re_path(r'^/refunds/(?P<pk>[0-9a-f-]{36})/disburse-cash/?$', RefundCashDisburseView.as_view(), name='refund-disburse-cash'),
    re_path(r'^/refunds/(?P<pk>[^/]+)/approve/?$', RefundApproveDisburseView.as_view(), name='refund-approve-disburse'),
    re_path(r'^/receipts/?$', BillingReceiptListView.as_view(), name='receipt-list'),
    re_path(r'^/credit-notes/?$', CreditNoteListView.as_view(), name='credit-note-list'),

    # Phase 2: Department Charge Integration & Hard Gates
    re_path(r'^/charges/emit/?$', DepartmentChargeEmitView.as_view(), name='charge-emit'),
    re_path(r'^/charges/queue/?$', DepartmentChargeQueueView.as_view(), name='charge-queue'),
    re_path(r'^/charges/cancel-event/?$', DepartmentChargeCancelView.as_view(), name='charge-cancel-event'),
    re_path(r'^/gates/check-clearance/?$', ClinicalGatingClearanceCheckView.as_view(), name='gate-check-clearance'),
    re_path(r'^/gates/rules/?$', DepartmentGatingRuleListUpdateView.as_view(), name='gate-rules-list-update'),

    # Tariffs, Packages & Corporate/TPA Pricing
    # Phase 6: governance routes come before /tariffs/{pk} so they are not read as tariff codes
    re_path(r'^/tariffs/change-requests/?$', TariffChangeRequestView.as_view(), name='tariff-change-requests'),
    re_path(r'^/tariffs/change-requests/(?P<pk>[0-9a-f-]{36})/decide/?$', TariffChangeDecideView.as_view(), name='tariff-change-decide'),
    re_path(r'^/tariffs/batch-import/?$', TariffBatchImportView.as_view(), name='tariff-batch-import'),
    re_path(r'^/tariffs/?$', TariffListCreateView.as_view(), name='tariff-list-create'),
    re_path(r'^/tariffs/(?P<pk>[^/]+)/?$', TariffDetailView.as_view(), name='tariff-detail'),
    re_path(r'^/packages/?$', ServicePackageListCreateView.as_view(), name='package-list-create'),
    re_path(r'^/packages/(?P<pk>[^/]+)/(?P<action>publish|retire)/?$', ServicePackageLifecycleView.as_view(), name='package-lifecycle'),
    re_path(r'^/packages/(?P<pk>[^/]+)/coverage/?$', ServicePackageCoverageView.as_view(), name='package-coverage'),
    re_path(r'^/packages/(?P<pk>[^/]+)/?$', ServicePackageDetailView.as_view(), name='package-detail'),
    re_path(r'^/pricing/markup-schedules/?$', MarkupScheduleListCreateView.as_view(), name='markup-schedule-list'),
    re_path(r'^/pricing/markup-schedules/(?P<pk>[0-9a-f-]{36})/?$', MarkupScheduleDetailView.as_view(), name='markup-schedule-detail'),
    re_path(r'^/corporate-accounts/?$', CorporateAccountListCreateView.as_view(), name='corporate-account-list-create'),
    re_path(r'^/corporate-accounts/(?P<pk>[^/]+)/?$', CorporateAccountDetailView.as_view(), name='corporate-account-detail'),
    re_path(r'^/pricing/calculate-quote/?$', PricingQuoteCalculateView.as_view(), name='pricing-calculate-quote'),

    # Frontline Cashier Workspace & Shift POS
    re_path(r'^/cashier/queue/?$', CashierQueueView.as_view(), name='cashier-queue'),

    # Phase 3: Billing Executive / Cashier Workspace
    re_path(r'^/cashier/dashboard/?$', CashierDashboardView.as_view(), name='cashier-dashboard'),
    re_path(r'^/cashier/live-queue/?$', CashierLiveQueueView.as_view(), name='cashier-live-queue'),
    re_path(r'^/cashier/patient-workspace/(?P<uhid>[^/]+)/?$', CashierPatientWorkspaceView.as_view(), name='cashier-patient-workspace'),
    re_path(r'^/cashier/bill-and-collect/?$', CashierBillAndCollectView.as_view(), name='cashier-bill-and-collect'),
    re_path(r'^/cashier/quick-walkin/?$', CashierQuickWalkinView.as_view(), name='cashier-quick-walkin'),
    re_path(r'^/cashier/tender-calculator/?$', CashierTenderCalculatorView.as_view(), name='cashier-tender-calculator'),
    re_path(r'^/cashier/discount-check/?$', DiscountGuardCheckView.as_view(), name='cashier-discount-check'),
    re_path(r'^/cashier/add-service/?$', CashierAddServiceView.as_view(), name='cashier-add-service'),
    re_path(r'^/cashier/add-service/(?P<pk>[^/]+)/remove/?$', CashierRemoveServiceView.as_view(), name='cashier-remove-service'),
    re_path(r'^/cashier/drafts/?$', CashierDraftCreateView.as_view(), name='cashier-draft-create'),
    re_path(r'^/cashier/drafts/(?P<pk>[^/]+)/discard/?$', CashierDraftDiscardView.as_view(), name='cashier-draft-discard'),
    re_path(r'^/cashier/drafts/(?P<pk>[^/]+)/collect/?$', CashierDraftCollectView.as_view(), name='cashier-draft-collect'),
    re_path(r'^/approvals/?$', ApprovalRequestListCreateView.as_view(), name='approval-list-create'),
    re_path(r'^/approvals/(?P<pk>[^/]+)/decide/?$', ApprovalRequestDecideView.as_view(), name='approval-decide'),
    re_path(r'^/shifts/open/?$', ShiftOpenView.as_view(), name='shift-open'),
    re_path(r'^/shifts/current/?$', ShiftCurrentView.as_view(), name='shift-current'),
    re_path(r'^/shifts/close/?$', ShiftCloseView.as_view(), name='shift-close'),

    # Phase 4: Counter Shift & Cash Control
    re_path(r'^/shifts/cash-pickup/?$', ShiftCashPickupView.as_view(), name='shift-cash-pickup'),
    re_path(r'^/shifts/supervisor-board/?$', ShiftSupervisorBoardView.as_view(), name='shift-supervisor-board'),
    re_path(r'^/shifts/vault-handover/?$', VaultHandoverView.as_view(), name='shift-vault-handover'),
    re_path(r'^/shifts/(?P<pk>[0-9a-f-]{36})/supervisor-signoff/?$', ShiftSupervisorSignoffView.as_view(), name='shift-supervisor-signoff'),

    # Phase 5: Billing Supervisor
    re_path(r'^/supervisor/dashboard/?$', SupervisorDashboardView.as_view(), name='supervisor-dashboard'),
    re_path(r'^/supervisor/approvals/?$', SupervisorApprovalQueueView.as_view(), name='supervisor-approvals'),
    re_path(r'^/supervisor/approvals/(?P<pk>[0-9a-f-]{36})/action/?$', SupervisorApprovalActionView.as_view(), name='supervisor-approval-action'),
    re_path(r'^/supervisor/refunds/?$', SupervisorRefundQueueView.as_view(), name='supervisor-refunds'),
    re_path(r'^/supervisor/refunds/(?P<pk>[0-9a-f-]{36})/(?:action|disburse)/?$', SupervisorRefundActionView.as_view(), name='supervisor-refund-action'),
    re_path(r'^/supervisor/counter-mode/?$', SupervisorCounterModeView.as_view(), name='supervisor-counter-mode'),
    re_path(r'^/supervisor/audit-stream/?$', SupervisorAuditStreamView.as_view(), name='supervisor-audit-stream'),
    re_path(r'^/supervisor/audit-stream/(?P<pk>[0-9a-f-]{36})/review/?$', SupervisorAuditReviewView.as_view(), name='supervisor-audit-review'),

    # Phase 7: Billing Admin Core & Governance
    re_path(r'^/admin/overview/?$', BillingAdminOverviewView.as_view(), name='billing-admin-overview'),
    re_path(r'^/admin/counters/?$', BillingAdminCountersView.as_view(), name='billing-admin-counters'),
    re_path(r'^/admin/counters/(?P<pk>[^/]+)/?$', BillingAdminCounterDetailView.as_view(), name='billing-admin-counter-detail'),
    re_path(r'^/admin/staff-roster/?$', BillingAdminStaffRosterView.as_view(), name='billing-admin-staff-roster'),
    re_path(r'^/admin/staff-roster/publish/?$', BillingAdminStaffRosterPublishView.as_view(), name='billing-admin-staff-roster-publish'),
    re_path(r'^/admin/approval-matrix/?$', BillingAdminApprovalMatrixView.as_view(), name='billing-admin-approval-matrix'),
    re_path(r'^/admin/approval-matrix/test-route/?$', BillingAdminApprovalMatrixTestRouteView.as_view(), name='billing-admin-approval-matrix-test-route'),
    re_path(r'^/admin/policies/?$', BillingAdminPoliciesView.as_view(), name='billing-admin-policies'),
    re_path(r'^/admin/policies/(?P<rule_code>[^/]+)/?$', BillingAdminPolicyDetailView.as_view(), name='billing-admin-policy-detail'),

    # Phase 8: Insurance / TPA + Corporate
    re_path(r'^/insurance/claims/?$', TPAClaimsListView.as_view(), name='tpa-claims-list-create'),
    re_path(r'^/insurance/claims/(?P<pk>[^/]+)/pre-auth/?$', TPAClaimPreAuthDetailView.as_view(), name='tpa-claim-pre-auth-detail'),
    re_path(r'^/insurance/claims/(?P<pk>[^/]+)/dossier/?$', TPAClaimDossierView.as_view(), name='tpa-claim-dossier'),
    re_path(r'^/insurance/calculate-split/?$', TPACoPaySplitCalculateView.as_view(), name='tpa-copay-split-calculate'),
    re_path(r'^/insurance/payers/?$', InsurancePayersListView.as_view(), name='insurance-payers-list'),
    re_path(r'^/corporate/accounts/?$', CorporateAccountsOverviewView.as_view(), name='corporate-accounts-overview'),
    re_path(r'^/corporate/vouchers/?$', CorporateVouchersListView.as_view(), name='corporate-vouchers-list-create'),
    re_path(r'^/corporate/vouchers/verify/?$', CorporateVoucherVerifyView.as_view(), name='corporate-voucher-verify'),

    # Phase 9: IPD Billing & Discharge Clearance
    re_path(r'^/ipd/admissions/?$', IPDAdmissionsOverviewView.as_view(), name='ipd-admissions-overview'),
    re_path(r'^/ipd/admissions/(?P<pk>[^/]+)/running-bill/?$', IPDRunningBillDetailView.as_view(), name='ipd-running-bill-detail'),
    re_path(r'^/ipd/admissions/(?P<pk>[^/]+)/ledger/add/?$', IPDRunningChargeAddView.as_view(), name='ipd-running-charge-add'),
    re_path(r'^/ipd/admissions/(?P<pk>[^/]+)/checklist/?$', IPDDischargeChecklistUpdateView.as_view(), name='ipd-discharge-checklist-update'),
    re_path(r'^/ipd/cron/accrue-daily-tariffs/?$', IPDDailyTariffAccrualCronView.as_view(), name='ipd-daily-tariff-accrual-cron'),
    re_path(r'^/ipd/interim-demand/?$', IPDInterimDemandView.as_view(), name='ipd-interim-demand'),
    re_path(r'^/ipd/final-bill/consolidate/?$', IPDFinalBillConsolidateView.as_view(), name='ipd-final-bill-consolidate'),
    re_path(r'^/ipd/discharge-clearance/issue/?$', IPDDischargeClearanceIssueView.as_view(), name='ipd-discharge-clearance-issue'),
    re_path(r'^/ipd/discharge-clearance/(?P<token>[^/]+)/verify/?$', IPDDischargeClearanceVerifyView.as_view(), name='ipd-discharge-clearance-verify'),

    # Phase 10: Revenue Integrity & Governance (A-03)
    re_path(r'^/integrity/overview/?$', RevenueIntegrityOverviewView.as_view(), name='revenue-integrity-overview'),
    re_path(r'^/integrity/leakages/?$', RevenueLeakageListView.as_view(), name='revenue-leakages-list'),
    re_path(r'^/integrity/leakages/scan/?$', RevenueLeakageScanView.as_view(), name='revenue-leakages-scan'),
    re_path(r'^/integrity/leakages/(?P<alert_id>[^/]+)/convert-charge/?$', RevenueLeakageConvertChargeView.as_view(), name='revenue-leakage-convert-charge'),
    re_path(r'^/integrity/leakages/(?P<alert_id>[^/]+)/dismiss/?$', RevenueLeakageDismissView.as_view(), name='revenue-leakage-dismiss'),
    re_path(r'^/integrity/leakages/(?P<alert_id>[^/]+)/assign/?$', RevenueLeakageAssignView.as_view(), name='revenue-leakage-assign'),
    re_path(r'^/integrity/risk-signals/?$', FraudRiskSignalListView.as_view(), name='fraud-risk-signals-list'),
    re_path(r'^/integrity/risk-signals/scan/?$', FraudRiskSignalScanView.as_view(), name='fraud-risk-signals-scan'),
    re_path(r'^/integrity/risk-signals/(?P<signal_id>[^/]+)/acknowledge/?$', FraudRiskSignalAcknowledgeView.as_view(), name='fraud-risk-signal-acknowledge'),
    re_path(r'^/integrity/investigations/?$', RevenueInvestigationListCreateView.as_view(), name='revenue-investigations-list-create'),
    re_path(r'^/integrity/investigations/(?P<case_id>[^/]+)(?:/update)?/?$', RevenueInvestigationDetailUpdateView.as_view(), name='revenue-investigation-detail-update'),

    # Phase 11: Reports, Period Close & Audit
    re_path(r'^/reports/catalogue/?$', ReportCatalogueView.as_view(), name='report-catalogue'),
    re_path(r'^/reports/run/(?P<key>[a-z_]+)/?$', ReportRunView.as_view(), name='report-run'),
    re_path(r'^/reports/revenue-analytics/?$', RevenueAnalyticsView.as_view(), name='report-revenue-analytics'),
    re_path(r'^/reports/daily-collections/?$', DailyCollectionsReportView.as_view(), name='report-daily-collections'),
    re_path(r'^/reports/department-revenue/?$', DepartmentRevenueReportView.as_view(), name='report-department-revenue'),
    re_path(r'^/reports/tax-gst/?$', TaxGstReportView.as_view(), name='report-tax-gst'),
    re_path(r'^/reports/aging-ar/?$', AgingReportView.as_view(), name='report-aging-ar'),
    re_path(r'^/reports/cashier-productivity/?$', CashierProductivityReportView.as_view(), name='report-cashier-productivity'),
    re_path(r'^/reports/journal/post/?$', SettlementJournalPostView.as_view(), name='report-journal-post'),
    re_path(r'^/reports/journal/live-stream/?$', LiveJournalStreamView.as_view(), name='report-journal-live-stream'),
    re_path(r'^/reports/department-revenue/live-summary/?$', LiveDepartmentRevenueSummaryView.as_view(), name='report-department-revenue-live-summary'),
    re_path(r'^/period-close/?$', PeriodCloseView.as_view(), name='period-close'),
    re_path(r'^/period-close/(?P<pk>[0-9a-f-]{36})/journal/?$', PeriodJournalView.as_view(), name='period-close-journal'),
    re_path(r'^/period-close/(?P<pk>[0-9a-f-]{36})/(?P<action>reopen-request|reopen-decision|relock)/?$', PeriodCloseActionView.as_view(), name='period-close-action'),
    re_path(r'^/audit-logs/?$', BillingAuditLogView.as_view(), name='audit-logs'),
    re_path(r'^/audit-logs/verify/?$', BillingAuditChainVerifyView.as_view(), name='audit-logs-verify'),
]
